/**
 *
 * Created by maixing on 2019/08/19 15:56:20
 *
 */

const toolBarConsts = {
	TOOLBAR_MULTI_SELECT: "TOOLBAR_MULTI_SELECT",
	TOOLBAR_SINGLE_SELECT: "TOOLBAR_SINGLE_SELECT",
	TOOLBAR_ADD_NODE: "TOOLBAR_ADD_NODE",
	TOOLBAR_ADD_EDGE: "TOOLBAR_ADD_EDGE",
	TOOLBAR_EDITE: "TOOLBAR_EDITE",
	TOOLBAR_CANCEL_EDITE: "TOOLBAR_CANCEL_EDITE"
};

export default toolBarConsts;
